// Generic runner for the five-step pipeline defined in steps.js.
//
// For each step: build input from previous validated outputs -> call provider ->
// parse JSON -> validate against the step's JSON Schema -> check cross-step invariants ->
// (on rejection) retry with the validator's errors as feedback, up to maxAttempts ->
// normalise deterministic fields -> persist output and state.json.

import { mkdir, rm } from 'node:fs/promises';
import path from 'node:path';
import { loadModelConfig, modelFor } from './config.js';
import { InputError, StepFailedError } from './errors.js';
import { exists, readJson, readText, writeJson } from './fsutil.js';
import { defaultRunId, SLUG_PATTERN } from './ids.js';
import { appendLearningLog, loadLearningLog } from './learning-log.js';
import { buildRetryInstruction, buildSystemPrompt, loadKnowledgeBase } from './prompts.js';
import { STEPS } from './steps.js';
import { createAjv, formatSchemaErrors, parseJsonOutput } from './validation.js';

/**
 * @typedef {import('./types.js').LlmProvider} LlmProvider
 * @typedef {import('./types.js').ChatMessage} ChatMessage
 * @typedef {import('./config.js').ModelConfig} ModelConfig
 * @typedef {import('./contracts.js').RunContext} RunContext
 * @typedef {import('./contracts.js').FinalOutput} FinalOutput
 * @typedef {import('./steps.js').StepContext} StepContext
 * @typedef {import('./steps.js').StepDefinition} StepDefinition
 * @typedef {import('ajv').ValidateFunction} ValidateFunction
 */

/** Policy statements added by code, never generated by the model. */
export const HONESTY_NOTES = Object.freeze([
  'Inputs are curated by hand from manual or public observations; there is no live connection to any social network.',
  'Memory is an append-only learning log, not a trained model.',
  'The system adapts observed patterns; it does not copy third-party content verbatim.',
  'Generated content is a starting point for human review, not a performance prediction.',
]);

/**
 * @typedef {object} RunOptions
 * @property {string} rootDir Directory containing engine/ and clients/.
 * @property {string} clientSlug
 * @property {LlmProvider} provider
 * @property {string} [runId] Defaults to `<slug>_<utc timestamp>`.
 * @property {string} [runsDir] Defaults to clients/<slug>/runs.
 * @property {boolean} [overwrite] Replace an existing run directory with the same id.
 * @property {number} [maxAttempts] Attempts per step (first try + retries). Default 2.
 * @property {ModelConfig} [modelConfig] Defaults to engine/config/models.json + env override.
 * @property {(message: string) => void} [log]
 * @property {() => Date} [now]
 */

/**
 * @typedef {object} StepState
 * @property {string} id
 * @property {'running' | 'completed' | 'failed'} status
 * @property {string} model
 * @property {number} attempts
 * @property {string} started_at
 * @property {string} [finished_at]
 * @property {string[][]} rejected_attempts Validation errors of each rejected attempt.
 * @property {string[]} adjustments Fields the engine recomputed after validation.
 */

/**
 * @typedef {object} RunState
 * @property {string} client
 * @property {string} run_id
 * @property {string} provider
 * @property {boolean} offline
 * @property {'running' | 'completed' | 'failed'} status
 * @property {string} started_at
 * @property {string} [completed_at]
 * @property {string} [failed_at]
 * @property {string} [error]
 * @property {StepState[]} steps
 * @property {{ calls: number, input_tokens: number, output_tokens: number }} usage_total
 */

/**
 * @typedef {object} RunResult
 * @property {string} runId
 * @property {string} runDir
 * @property {RunState} state
 * @property {FinalOutput} final
 */

/**
 * @param {ReturnType<typeof createAjv>} ajv
 * @param {string} engineDir
 * @param {string} clientDir
 * @returns {Promise<RunContext>}
 */
async function loadRunContext(ajv, engineDir, clientDir) {
  const schema = /** @type {object} */ (
    await readJson(path.join(engineDir, 'schemas', 'input', 'run_context.schema.json'))
  );
  const validate = ajv.compile(schema);
  const data = await readJson(path.join(clientDir, 'run_context.json'));
  if (!validate(data)) {
    const problems = formatSchemaErrors(validate.errors).join('; ');
    throw new InputError(`run_context.json of client "${path.basename(clientDir)}" is invalid: ${problems}`);
  }
  return /** @type {RunContext} */ (data);
}

/**
 * @param {string} text
 * @param {ValidateFunction} validate
 * @param {StepDefinition} step
 * @param {StepContext} ctx
 * @returns {{ ok: true, value: unknown } | { ok: false, errors: string[] }}
 */
function validateOutput(text, validate, step, ctx) {
  const parsed = parseJsonOutput(text);
  if (!parsed.ok) return parsed;
  if (!validate(parsed.value)) {
    return { ok: false, errors: formatSchemaErrors(validate.errors) };
  }
  const violations = step.check(parsed.value, ctx);
  if (violations.length > 0) return { ok: false, errors: violations };
  return parsed;
}

/**
 * @param {string} text
 * @param {number} limit
 */
function truncate(text, limit) {
  return text.length <= limit ? text : `${text.slice(0, limit)}\n[truncated]`;
}

/**
 * Runs the five steps for one client and persists every output under the run directory.
 * Throws InputError before any model call if the client input is invalid, ProviderError if
 * the provider fails, StepFailedError if a step exhausts its attempts. On failure, state.json
 * is marked failed and ERROR.json is written; nothing is fabricated for the failed step.
 * @param {RunOptions} options
 * @returns {Promise<RunResult>}
 */
export async function runPipeline(options) {
  const { rootDir, clientSlug, provider } = options;
  const log = options.log ?? (() => {});
  const now = options.now ?? (() => new Date());
  const maxAttempts = options.maxAttempts ?? 2;
  if (!Number.isInteger(maxAttempts) || maxAttempts < 1) {
    throw new InputError('maxAttempts must be a positive integer');
  }
  if (!SLUG_PATTERN.test(clientSlug)) throw new InputError(`invalid client slug "${clientSlug}"`);
  const runId = options.runId ?? defaultRunId(clientSlug, now());
  if (!SLUG_PATTERN.test(runId)) throw new InputError(`invalid run id "${runId}"`);

  const engineDir = path.join(rootDir, 'engine');
  const clientDir = path.join(rootDir, 'clients', clientSlug);
  if (!(await exists(clientDir))) {
    throw new InputError(
      `client "${clientSlug}" not found in clients/. Create it with: npm run new-client -- ${clientSlug}`,
    );
  }

  // Load and validate everything before the first model call.
  const ajv = createAjv();
  const runContext = { ...(await loadRunContext(ajv, engineDir, clientDir)), run_id: runId };
  const competitorContext = await readJson(path.join(clientDir, 'competitor_context.json'));
  const contextNotes = await readText(path.join(clientDir, 'context.md'));
  const learningLog = await loadLearningLog(clientDir);
  const knowledgeBase = await loadKnowledgeBase(engineDir);
  const modelConfig = options.modelConfig ?? (await loadModelConfig(rootDir));
  const prepared = [];
  for (const step of STEPS) {
    const schema = /** @type {Record<string, unknown>} */ (
      await readJson(path.join(engineDir, 'schemas', step.schemaFile))
    );
    const prompt = await readText(path.join(engineDir, 'agents', step.promptFile));
    prepared.push({
      step,
      schema,
      validate: ajv.compile(schema),
      system: buildSystemPrompt({
        prompt,
        knowledgeBase: step.usesKnowledgeBase ? knowledgeBase : null,
        schema,
      }),
      config: modelFor(modelConfig, step.id),
    });
  }

  // Offline runs never share a directory with real runs.
  const runsDir = options.runsDir ?? path.join(clientDir, 'runs');
  const runDir = path.join(runsDir, provider.offline ? `${runId}__mock` : runId);
  if (await exists(runDir)) {
    if (!options.overwrite) {
      throw new InputError(`run directory already exists: ${runDir} (use overwrite to replace it)`);
    }
    await rm(runDir, { recursive: true, force: true });
  }
  await mkdir(runDir, { recursive: true });
  const statePath = path.join(runDir, 'state.json');

  /** @type {RunState} */
  const state = {
    client: clientSlug,
    run_id: runId,
    provider: provider.name,
    offline: provider.offline,
    status: 'running',
    started_at: now().toISOString(),
    steps: [],
    usage_total: { calls: 0, input_tokens: 0, output_tokens: 0 },
  };
  await writeJson(statePath, state);

  /** @type {StepContext} */
  const ctx = { runId, runContext, competitorContext, contextNotes, learningLog, outputs: {} };

  try {
    for (const { step, schema, validate, system, config } of prepared) {
      /** @type {StepState} */
      const stepState = {
        id: step.id,
        status: 'running',
        model: provider.offline ? `${provider.name} (offline)` : config.model,
        attempts: 0,
        started_at: now().toISOString(),
        rejected_attempts: [],
        adjustments: [],
      };
      state.steps.push(stepState);
      await writeJson(statePath, state);
      log(`> ${step.id}`);

      /** @type {ChatMessage[]} */
      const baseMessages = [{ role: 'user', content: JSON.stringify(step.buildInput(ctx), null, 2) }];
      let messages = baseMessages;
      /** @type {unknown} */
      let accepted;
      let isAccepted = false;

      while (stepState.attempts < maxAttempts) {
        stepState.attempts += 1;
        state.usage_total.calls += 1;
        const response = await provider.complete({
          stepId: step.id,
          model: config.model,
          maxTokens: config.maxTokens,
          reasoningEffort: config.reasoningEffort,
          system,
          messages,
          schema,
        });
        state.usage_total.input_tokens += response.usage?.inputTokens ?? 0;
        state.usage_total.output_tokens += response.usage?.outputTokens ?? 0;

        const result = validateOutput(response.text, validate, step, ctx);
        if (result.ok) {
          accepted = result.value;
          isAccepted = true;
          break;
        }
        stepState.rejected_attempts.push(result.errors);
        await writeJson(statePath, state);
        log(`  ! ${step.id} attempt ${stepState.attempts} rejected (${result.errors.length} problem(s))`);
        messages = [
          ...baseMessages,
          { role: 'assistant', content: truncate(response.text, 4000) },
          { role: 'user', content: buildRetryInstruction(result.errors) },
        ];
      }
      if (!isAccepted) throw new StepFailedError(step.id, stepState.rejected_attempts);

      let value = accepted;
      if (step.normalize) {
        const normalized = step.normalize(value, ctx);
        value = normalized.value;
        stepState.adjustments.push(...normalized.adjustments);
      }
      if (step.id === 'orchestrator') {
        value = { .../** @type {object} */ (value), honesty_notes: [...HONESTY_NOTES] };
      }
      /** @type {Record<string, unknown>} */ (ctx.outputs)[step.id] = value;
      await writeJson(path.join(runDir, step.outputFile), value);

      stepState.status = 'completed';
      stepState.finished_at = now().toISOString();
      await writeJson(statePath, state);
      log(`  ok ${step.id} (attempts: ${stepState.attempts}, adjustments: ${stepState.adjustments.length})`);
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    const current = state.steps.at(-1);
    if (current && current.status === 'running') {
      current.status = 'failed';
      current.finished_at = now().toISOString();
    }
    state.status = 'failed';
    state.failed_at = now().toISOString();
    state.error = message;
    await writeJson(statePath, state);
    await writeJson(path.join(runDir, 'ERROR.json'), {
      step: current?.id ?? null,
      type: error instanceof Error ? error.name : 'Error',
      message,
      rejected_attempts: error instanceof StepFailedError ? error.attemptErrors : [],
      at: state.failed_at,
    });
    throw error;
  }

  state.status = 'completed';
  state.completed_at = now().toISOString();
  await writeJson(statePath, state);

  const final = /** @type {FinalOutput} */ (ctx.outputs.orchestrator);
  if (!provider.offline) {
    await appendLearningLog(clientDir, runId, final.learning_log_entry, now());
  }
  return { runId, runDir, state, final };
}
